### ISSUE TITLE
DR53N allele

### ISSUE THREAD

**Issue by nataliadb** [delordson/SureTyperODT#4]
Hi Delordson, my team have pointed out to me that the DRB4*01:03:01:02N is importing as 01:03N, which apparently ODT don't like. I've checked the XML file and it does give the full allele. Please can you incorporate the import? I'll send the fXML file by nhs.net. Thanks, Natalia

**Comment by delordson** [comment]
Thanks Natalia, Yes I can confirm that we have been truncating to 01:03N. Didn't realise ODT were not happy with this. If they are happy with the full allele we can see if we can bring that in.

**Comment by SPEACOCK2018** [comment]
ODT Informed us they have done an update to their system so it should now accept the format 01:03N

**Comment by delordson** [comment]
No longer an issue.
