### ISSUE TITLE
Alter allele strings

### ISSUE THREAD

**Issue by EmmaWhite** [delordson/SureTyperODT#6]
Email from Jess: 23/01/2018

It's tricky isn't it!

I also like having two alleles in the string, but wonder if it would be simpler just to have one and /XX. The serology is there so that people should know that a DQB1*03:01/XX string does not include DQB1*03:02/03:03 etc. 

We have also noticed that if a second common allele is present in different serologically defined antigen string, it is not included. E.g. below; this result is recorded as C*04:01/07 – which implies it is not C*04:04. 

 

With 2 alleles we are providing more information that we are required to and taking responsibility for a slightly higher resolution type than we need to. Would it be safer to just give one and other labs contact us if they require further info? 

Just rambling thoughts – don’t know the answer. 

Home time now. 

Anyone going to the renal meeting tomorrow? See you there if you are.

Hope all well

Jess

**Comment by delordson** [comment]
Dear All,

Just about to make this change so that all results will import only the first allele followed by /XX to indicate that other alleles not excluded and not give the impression we have typed to high resolution. Any objections?

**Comment by delordson** [comment]
Fixed in v12.
