### ISSUE TITLE
DR51/52/53 import when no DRB3/4/5 detected

### ISSUE THREAD

**Issue by kmounsey** [delordson/SureTyperODT#8]
When no DRB3/4/5 genes are detected (e.g. DRB1*01 homozygous), 't tected' appears in DR51/52/53 box. Assuming this is 'not detected'.

**Comment by delordson** [comment]
Sorry only just spotted this. Not sure why I didn't receive an email. Can you send me a copy of the xml file please to dkallon1@nhs.net

**Comment by delordson** [comment]
This is fixed in v14.
